[package]
name = "partitions-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
num-integer = "0.1.46"
indicatif = "0.17.9"
rulinalg = "0.4.2"
rayon = "1.10.0"
clap = { version = "4.5.23", features = ["derive"] }
